apiVersion: v1
kind: Pod
metadata:
  name: flower6-pod
  namespace: ashutosh-ns
  labels:
    app: flower6
spec:
  containers:
    - name: flower6-pod-container
      image: ashutosh4782/flower6:latest
      ports:
        - containerPort: 3015

