apiVersion: v1
kind: pod
metadata:
  name: ey-pod
  namespace: ashutosh-ns
  labels:
    app: ey-cart
spec:
  containers:
    - name: ey-pod-container
      image: muralisocial123/ey-cart:v1.1.0
      ports:
        - containerPort: 3000



