apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flower6-rs
  namespace: ashutosh-ns
  labels:
    app: flower6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flower6              # MUST match template.metadata.labels exactly
  template:
    metadata:
      labels:
        app: flower6
    spec:
      containers:
        - name: flower6-container
          image: ashutosh4782/flower6:latest
          ports:
            - containerPort: 3015

